title: Crackmes.one Blog
description: Official blog of crackmes.one - the reverse engineering community
url: "https://blog.crackmes.one"
baseurl: ""

# Theme
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from processing
exclude:
  - LICENSE
  - README.md
